#!/bin/bash

# variables
PROJ_DIR=/home/maxjiang/Codes/project_sdfgan
JOB_DIR=${PROJ_DIR}/sdfgan/jobs/job0-shapenet-car

DATASET_DIR=${PROJ_DIR}/sdfgan/data
LOG_DIR=${JOB_DIR}/logs
SAMPLE_DIR=${JOB_DIR}/samples
CHECKPOINT_DIR=${JOB_DIR}/checkpoint

# execute
python main.py \
--batch_size=64 \
--dataset_dir=${DATASET_DIR} \
--log_dir=${LOG_DIR} \
--sample_dir=${SAMPLE_DIR} \
--checkpoint_dir=${CHECKPOINT_DIR} \
--dataset=shapenet_car
