#!/bin/bash

# variables
PROJ_DIR=/home/maxjiang/Codes/project_sdfgan
JOB_DIR=${PROJ_DIR}/sdfgan_data/jobs/job0-vaegan

DATASET_DIR=${PROJ_DIR}/sdfgan_data/data
LOG_DIR=${JOB_DIR}/logs
SAMPLE_DIR=${JOB_DIR}/samples
CHECKPOINT_DIR=${JOB_DIR}/checkpoint

# execute
python main.py \
--is_new \
--epoch=1000 \
--batch_size=32 \
--e_learning_rate=0.0002 \
--g_learning_rate=0.0002 \
--d_learning_rate=0.0001 \
--dataset_dir=${DATASET_DIR} \
--log_dir=${LOG_DIR} \
--sample_dir=${SAMPLE_DIR} \
--checkpoint_dir=${CHECKPOINT_DIR} \
--num_gpus=4 \
--dataset=shapenet_car \
--is_train \
--field_constraint=.0
